apiVersion: apps/v1
kind: Deployment
metadata:
  name: technical-test-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: technical-test-k8s
  template:
    metadata:
      labels:
        app: technical-test-k8s
    spec:
      containers:
      - image: technical-test-docker.jar:v3.0
        name: technical-test-docker-container
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8081